apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'  # Self-monitoring job
      metrics_path: '/metrics'
      static_configs:
        - targets: ['localhost:9090']  # Scrape itself
      # Optional: Add relabeling for cleaner metrics
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance
          replacement: 'prometheus-server'
