apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kafka-exporter'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['kafka-exporter.monitoring.svc.cluster.local:8000']