apiVersion: v1
kind: Service
metadata:
  name: redpanda-exporter
  namespace: monitoring
  labels:
    app: redpanda-exporter
spec:
  selector:
    app: redpanda-exporter
  ports:
    - port: 8001
      targetPort: 8000
      protocol: TCP